kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/jereksel/go-sonatype-nexus

steps:
- name: test
  image: golang
  environment:
    CI: "true"
    NEXUS_HOSTNAME: "nexus"
  commands:
  - ./wait_for_nexus.sh $NEXUS_HOSTNAME
  - go test -race -coverprofile=coverage.txt -covermode=atomic

- name: coverage
  image: plugins/codecov
  settings:
    files:
     - coverage.txt
    token:
      from_secret: CODECOV_TOKEN

services:
- name: nexus
  image: sonatype/nexus3:3.14.0